<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>DualHedgeFast2RV72CryptoCostSafe</AssemblyName>
    <AlgoName>Dual_Hedge_FAST_2R_V7_2_CRYPTO_COST_SAFE</AlgoName>
    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.21" />
  </ItemGroup>
</Project>
