plugins {
    id 'com.android.application'
}

android {
    namespace 'com.khutwa.noorhelper'
    compileSdk 35

    defaultConfig {
        applicationId 'com.khutwa.noorhelper.auto062'
        minSdk 23
        targetSdk 34
        versionCode 13
        versionName '0.6.2'
    }

    signingConfigs {
        debug {
            enableV1Signing true
            enableV2Signing true
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
